/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4ae5dfa4-e8f6-4e79-b1d9-5574979ba161",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_1eubUaVL4",
    "aws_user_pools_web_client_id": "4ell1necc8o3dknqegfr66numm",
    "oauth": {}
};


export default awsmobile;
